version: '3.7'
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: student-crm-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: student-crm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: student-crm-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student-crm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
