import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {CourseProvider} from "@/app/contexts/CourseContext";
import {StudentProvider} from "@/app/contexts/StudentContext";
import {ThemeProvider} from "@mui/material";
import theme from "@/app/styles/theme";
import {SnackbarProvider} from "@/app/contexts/SnackbarContext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Student CRM",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeProvider theme={theme}>
            <SnackbarProvider>
                <CourseProvider>
                    <StudentProvider>
                        {children}
                    </StudentProvider>
                </CourseProvider>
            </SnackbarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
